### ISSUE TITLE
SEO Tab 2 installation fails in HHVM

### ISSUE THREAD

**Issue by gpsietzema** [Sterc/SEOTab#108]
Installation just fails in HHVM. It is unable to create the seo_urls table. Probably due to a function call on a non-existant object or something like that.

Last bug which prevents a release ;)

Local strack trace below. HHVM Version 3.17.2.
`\nFatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42000] [1065] Query was empty' in /var/www/vhosts/sterc/private/core/xpdo/xpdo.class.php:2552\nStack trace:\n#0 /var/www/vhosts/sterc/private/core/xpdo/xpdo.class.php(2552): PDO->query()\n#1 /var/www/vhosts/sterc/private/core/components/stercseo/processors/mgr/redirect/migrate.class.php(57): xPDO->query()\n#2 /var/www/vhosts/sterc/private/core/model/modx/modprocessor.class.php(173): StercSeoMigrateProcessor->process()\n#3 /var/www/vhosts/sterc/private/core/model/modx/modx.class.php(1704): modProcessor->run()\n#4 /var/www/vhosts/sterc/private/core/model/modx/modconnectorresponse.class.php(140): modX->runProcessor()\n#5 /var/www/vhosts/sterc/private/core/model/modx/modconnectorrequest.class.php(82): modConnectorResponse->outputContent()\n#6 /var/www/vhosts/sterc/private/core/model/modx/modconnectorrequest.class.php(69): modConnectorRequest->prepareResponse()\n#7 /var/www/vhosts/sterc/webroot/assets/components/stercseo/connector.php(42): modConnectorRequest->handleRequest()\n#8 {main}`

**Comment by gpsietzema** [comment]
Never mind, this is a MODX issue. Same happens in Gallery-extra:

`\nWarning: Session callback expects true/false return value in /var/www/vhosts/revo25x/core/model/modx/modx.class.php on line 2291
\nFatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S02] [1146] Table 'revo25x.modx_gallery_items' doesn't exist' in /var/www/vhosts/revo25x/core/xpdo/xpdo.class.php:2540\nStack trace:\n#0 /var/www/vhosts/revo25x/core/xpdo/xpdo.class.php(2540): PDO->query()\n#1 /var/www/vhosts/revo25x/core/xpdo/om/mysql/xpdomanager.class.php(131): xPDO->query()\n#2 /var/www/vhosts/revo25x/core/packages/gallery-1.7.0-pl/modMenu/f79ae265188794f2f5e06542a510c8ea.resolve.tables.resolver(37): xPDOManager_mysql->createObjectContainer()\n#3 /var/www/vhosts/revo25x/core/xpdo/transport/xpdovehicle.class.php(226): include()\n#4 /var/www/vhosts/revo25x/core/xpdo/transport/xpdoobjectvehicle.class.php(227): xPDOVehicle->resolve()\n#5 /var/www/vhosts/revo25x/core/xpdo/transport/xpdoobjectvehicle.class.php(88): xPDOObjectVehicle->_installObject()\n#6 /var/www/vhosts/revo25x/core/xpdo/transport/xpdotransport.class.php(269): xPDOObjectVehicle->install()\n#7 /var/www/vhosts/revo25x/core/model/modx/transport/modtransportpackage.class.php(305): xPDOTransport->install()\n#8 /var/www/vhosts/revo25x/core/model/modx/processors/workspace/packages/install.class.php(42): modTransportPackage->install()\n#9 /var/www/vhosts/revo25x/core/model/modx/modprocessor.class.php(173): modPackageInstallProcessor->process()\n#10 /var/www/vhosts/revo25x/core/model/modx/modx.class.php(1704): modProcessor->run()\n#11 /var/www/vhosts/revo25x/core/model/modx/modconnectorresponse.class.php(140): modX->runProcessor()\n#12 /var/www/vhosts/revo25x/core/model/modx/modconnectorrequest.class.php(82): modConnectorResponse->outputContent()\n#13 /var/www/vhosts/revo25x/core/model/modx/modconnectorrequest.class.php(69): modConnectorRequest->prepareResponse()\n#14 /var/www/vhosts/revo25x/connectors/index.php(77): modConnectorRequest->handleRequest()\n#15 {main}
`
